### ISSUE TITLE
Impossible to set titles on tabs (version 8.0.0a4)

### ISSUE THREAD

**Issue by PierreCe** [jupyter-widgets/ipywidgets#3210]
## Description

Documentation example does not show titles on tabs

## Reproduce

```
print (widgets.__version__)
tab_contents = ['P0', 'P1', 'P2', 'P3', 'P4']
children = [widgets.Text(description=name) for name in tab_contents]
tab = widgets.Tab()
tab.children = children
tab.titles = [str(i) for i in range(len(children))]
display(tab)

```
![image](https://user-images.githubusercontent.com/79575515/121321778-b185e780-c90e-11eb-9b06-0dfea260b83f.png)

set_titles method is not implemented anymore :
`tab.set_titles(0,'0')`

AttributeError                            Traceback (most recent call last)
<ipython-input-42-a36402215f28> in <module>
----> 1 tab.set_titles(0,'0')

AttributeError: 'Tab' object has no attribute 'set_titles'

so, similar issues doesn't apply (#2790, #2868)

**Comment by PierreCe** [comment]
After downgrading to 8.0.3a for test, re-install 8.0.4a, relaunch jupyter, the titles appeared !

Don't know why, but it works.

**Comment by PierreCe** [comment]
After downgrading to 8.0.3a for test, re-install 8.0.4a, relaunch jupyter, the titles appeared !

Don't know why, but it work

**Comment by cuihantao** [comment]
I ran into the exact same issue running ipywidgets 7.6.5, notebook 6.4.8 and 6.1.6. Any suggestions? @jtpio Thanks!

**Comment by jasongrout** [comment]
> I ran into the exact same issue running ipywidgets 7.6.5, notebook 6.4.8 and 6.1.6. Any suggestions? @jtpio Thanks!

This syntax only works in 8.0, not in 7.x. For 7.x, please use the `set_title` syntax in the 7.x documentation: https://ipywidgets.readthedocs.io/en/stable/examples/Widget%20List.html#Tabs

**Comment by rd5802** [comment]
Hi,

probably related. Tabs arent rendered. 
Is it Jupyterlb version related? Im running Jupyterlab 3.2.9

import ipywidgets as widgets
print (widgets.__version__)
tab_contents = ['P0', 'P1', 'P2', 'P3', 'P4']
children = [widgets.Text(description=name) for name in tab_contents]
tab = widgets.Tab()
tab.children = children
tab.titles = [str(i) for i in range(len(children))]
display(tab)


![image](https://user-images.githubusercontent.com/35902744/212931564-371748b3-4cfc-4773-a908-167e9f7b34bd.png)
