### ISSUE TITLE
AttributeError: module 'ipywidgets' has no attribute 'SelectionRangeSlider'

### ISSUE THREAD

**Issue by mbk0asis** [jupyter-widgets/ipywidgets#2873]
Hi!

I'm having trouble in running 'SelectionRangeSlider' after updating my system (Ubuntu 18.04 to 20.04).
This is the error I'm getting, "AttributeError: module 'ipywidgets' has no attribute 'SelectionRangeSlider'"

I tried to solve this by reinstalling 'ipywidgets' (updated 6.0.0 > 7.5.1), but still get the same error.

Here is the code, I have for 'SelectionRangeSlider'. 
You can find the [original code from here.](https://nbviewer.jupyter.org/github/broadinstitute/wot/blob/master/notebooks/Notebook-1-FLE-cell_sets-gene_sets.ipynb) 

```
day_selector = widgets.SelectionRangeSlider(
    options=unique_days,
    continuous_update=False,
    index=(0,len(unique_days)-1),
    description='Days'
)
```
