### ISSUE TITLE
ipykernel error with ipywidgets 8.1 and jupyterlite

### ISSUE THREAD

**Issue by jsignell** [jupyter-widgets/ipywidgets#3819]
## Description

ipywidgets 8.1 raises error with ipykernel

```python-traceback
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 from ipywidgets import IntSlider

File /lib/python3.11/site-packages/ipywidgets/__init__.py:54
     51         return
     52     register_comm_target()
---> 54 _handle_ipython()

File /lib/python3.11/site-packages/ipywidgets/__init__.py:52, in _handle_ipython()
     50 if ip is None:
     51     return
---> 52 register_comm_target()

File /lib/python3.11/site-packages/ipywidgets/__init__.py:41, in register_comm_target(kernel)
     39 """Register the jupyter.widget comm target"""
     40 from . import comm
---> 41 comm_manager = comm.get_comm_manager()
     42 if comm_manager is None:
     43     return

File /lib/python3.11/site-packages/ipywidgets/comm.py:18, in get_comm_manager()
     17 def get_comm_manager():
---> 18     if requires_ipykernel_shim():
     19         ip = get_ipython()
     21         if ip is not None and getattr(ip, "kernel", None) is not None:

File /lib/python3.11/site-packages/ipywidgets/comm.py:11, in requires_ipykernel_shim()
      8 if "ipykernel" in sys.modules:
      9     import ipykernel
---> 11     version = ipykernel.version_info
     12     return version < (6, 18)
     13 else:

AttributeError: module 'ipykernel' has no attribute 'version_info'
```

![image](https://github.com/jupyter-widgets/ipywidgets/assets/4806877/53be686c-a8f5-4bf7-8814-cdcbe267bb8c)

## Reproduce

1. Go to https://jupyterlite.github.io/demo/lab/index.html?path=pyodide/interactive-widgets.ipynb
2. Run cells

I ran into this while running the examples on https://jupyterlite.github.io/demo/lab/index.html

## Expected behavior

Examples work as expected with ipywidgets==8.0
![Screenshot from 2023-08-01 12-53-12](https://github.com/jupyter-widgets/ipywidgets/assets/4806877/23899119-a0f6-4de1-9c9b-862d86cb22f1)

**Comment by rowanc1** [comment]
Running into the same error in jupyter_lite with mystmd.org embedding of widgets, which worked with `v8.0`.

**Comment by martinRenou** [comment]
In order to fix this, the pyodide kernel in jupyterlite needs to update its ipykernel mock package here to include a mock of this version_info. See https://github.com/jupyterlite/pyodide-kernel/tree/main/packages/pyodide-kernel/py/ipykernel/ipykernel

Happy to review a PR, I can also do it myself later this week.

**Comment by jtpio** [comment]
> update its ipykernel mock package here to include a mock of this version_info

Wouldn't it be possible to remove the mock if `ipykernel` was removed in https://github.com/jupyter-widgets/ipywidgets/pull/3811?

**Comment by martinRenou** [comment]
Thinking about it, removing the mock of ipykernel means breaking support for old version of ipywidgets that were still relying on importing ipykernel stuffs.

If that is fine for you, then I can indeed remove the ipykernel mock and make use of the comm module. Otherwise, updating the mock to include a version_info variable may be the way to go for now.

**Comment by jtpio** [comment]
> Otherwise, updating the mock to include a version_info variable may be the way to go for now.

Ah maybe that's indeed the easiest and less disruptive path for now :+1: 

We could try using the `comm` package in a `0.1.0` release of `jupyterlite-pyodide-kernel` (current still on `0.0.x`).

**Comment by jtpio** [comment]
Just released `jupyterlite-pyodide-kernel==0.0.10`: https://github.com/jupyterlite/pyodide-kernel/releases/tag/v0.0.10

And updated the demo repo to use this version:

![image](https://github.com/jupyter-widgets/ipywidgets/assets/591645/0e2ccc7a-c23b-437f-87be-618fc56538cd)

**Comment by rowanc1** [comment]
Thank you! These are working again in myst!
https://rowanc1.github.io/myst-lite/interactive-articles

![lorenz](https://github.com/jupyter-widgets/ipywidgets/assets/913249/2559fdf9-f2d9-46ec-89eb-fc648dec054d)
